package goragflow

import (
	"context"
	"errors"
	"net/http"

	"github.com/danilsolovyov/go-ragflow/options"
	"github.com/danilsolovyov/go-ragflow/parameters"
)

// TODO: autogenerated need handle refactoring.
type Agent struct {
	Avatar      interface{} `json:"avatar"`
	CanvasType  interface{} `json:"canvas_type"`
	CreateDate  string      `json:"create_date"`
	CreateTime  int64       `json:"create_time"`
	Description interface{} `json:"description"`
	DSL         DSL         `json:"dsl"`
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	UpdateDate  string      `json:"update_date"`
	UpdateTime  int64       `json:"update_time"`
	UserID      any         `json:"user_id"`
	sessionID   string      `json:"-"`
	client      *Client     `json:"-"`
}

func NewAgent(id string, client *Client) *Agent {
	return &Agent{
		ID:     id,
		client: client,
	}
}

// GetAgents retrieves a list of agents with the specified options.
// It merges the provided options with default values and makes a GET request to the agents endpoint.
//
// @param ctx context.Context - The context for the request.
// @param opts *options.GetAgentsOptions - Options for filtering, pagination, and sorting agents.
// @return []*Agent - A slice of Agent pointers representing the retrieved agents.
// @return error - An error if the request fails.
func (c *Client) GetAgents(ctx context.Context, opts *options.GetAgentsOptions) ([]*Agent, error) {
	path := "/agents"
	opts = options.DefaultGetAgentsOptions().Merge(opts)
	params := opts.Parameters()

	result := []*Agent{}
	err := c.do(ctx, http.MethodGet, path, nil, params...)
	if err != nil {
		return nil, err
	}

	for _, item := range result {
		item.client = c
	}

	return result, nil
}

// GetAgent retrieves an agent with the specified ID.
// It makes a GET request to the agents endpoint with the ID as a path parameter.
//
// @param ctx context.Context - The context for the request.
// @param id string - The ID of the agent to retrieve.
// @return *Agent - A pointer to the Agent.
// @return error - An error if the request fails.
func (c *Client) GetAgent(ctx context.Context, id string) (*Agent, error) {
	agents, err := c.GetAgents(ctx, &options.GetAgentsOptions{ID: id})
	if err != nil {
		return nil, err
	}

	if len(agents) == 0 {
		return nil, errors.New("agent not found")
	}

	agent := agents[0]
	agent.client = c

	return agent, nil
}

// getMe retrieves the current agent's details from the client and updates the agent instance.
//
// @param ctx The context for the operation.
// @return An error if the agent is not found or if there is a client error.
func (a *Agent) getMe(ctx context.Context) error {
	agents, err := a.client.GetAgents(ctx, &options.GetAgentsOptions{ID: a.ID})
	if err != nil {
		return err
	}

	if len(agents) == 0 {
		return errors.New("agent not found")
	}

	found := agents[0]
	found.client = a.client
	a = found

	return nil
}

// GetMe retrieves this agent.
//
// @param ctx context.Context - The context for the request.
// @return *Agent - A pointer to the Agent.
// @return error - An error if the request fails.
func (a *Agent) GetMe(ctx context.Context) (*Agent, error) {
	err := a.getMe(ctx)
	if err != nil {
		return nil, err
	}

	return a, nil
}

// ListSessions retrieves a list of sessions for this agent.
//
// @param ctx context.Context - The context for the request.
// @param opts *options.ListAgentSessionsOptions - Options for filtering, pagination, and sorting sessions.
// @return []Session - A slice of Session objects representing the retrieved sessions.
// @return error - An error if the request fails.
func (a *Agent) ListSessions(ctx context.Context, opts *options.ListAgentSessionsOptions) ([]Session, error) {
	path := "/agents/:agent_id/sessions"
	opts = options.DefaultListAgentSessionsOptions().Merge(opts)
	opts.SetAgentID(a.ID)
	params := opts.Parameters()

	result := []Session{}

	err := a.client.do(ctx, http.MethodGet, path, &result, params...)
	if err != nil {
		return nil, err
	}

	return result, nil
}

// CreateSession creates a new session for this agent.
//
// @param ctx context.Context - The context for the request.
// @param opts *options.CreateAgentSessionOptions - Options for creating the session.
// @return *Session - A pointer to the created Session object.
// @return error - An error if the request fails.
func (a *Agent) CreateSession(ctx context.Context, opts *options.CreateAgentSessionOptions) (*Session, error) {
	path := "/agents/:agent_id/sessions"

	params := []parameters.Parameter{
		parameters.NewPathParameter("agent_id", a.ID),
		parameters.NewQueryParameter("user_id", opts.UserID),
	}

	var result Session

	err := a.client.do(ctx, http.MethodPost, path, &result, params...)
	if err != nil {
		return nil, err
	}

	a.sessionID = result.ID

	return &result, nil
}

// SetSessionID sets the session ID for the agent.
//
// @param sessionID The session ID to be set for the agent.
func (a *Agent) SetSessionID(sessionID string) {
	a.sessionID = sessionID
}

// Completions generates completions for the given prompt using the agent's model.
//
// @param ctx context.Context - The context for the request.
// @param opts *options.CompletionsOptions - The options for the completions request.
func (a *Agent) Completions(ctx context.Context, opts *options.AgentCompletionsOptions) (*Completions, error) {
	path := "/agents/:agent_id/completions"
	opts = options.DefaultAgentCompletionsOptions().Merge(opts)
	opts.SetAgentID(a.ID)

	if a.sessionID != "" {
		opts.SetSessionID(a.sessionID)
	}

	params := opts.Parameters()

	var result Completions

	err := a.client.do(ctx, http.MethodPost, path, &result, params...)
	if err != nil {
		return nil, err
	}

	a.sessionID = result.SessionID

	return &result, nil
}
